Revised/Revised/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('RevisedApp.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Revised/RevisedApp/urls.py
from django.urls import path
from RevisedApp import views
from django.contrib.auth import views as ad  

urlpatterns=[
path('',views.homepage,name='home'),
path('lg/',ad.LoginView.as_view(template_name="html/login.html"),name='log'),
path('lgout/',ad.LogoutView.as_view(template_name="html/logout.html"),name='logo'),
path('reg/',views.register,name='reges'),
path('rol/',views.role,name='main'),
path('req/',views.requestform,name='request'),
path('per/',views.permissions,name='perm'),
path('eper/<int:k>/',views.gvper,name='gp'),
path('das/',views.dashboard,name='dash'),
path('jobs/',views.jobposts,name='job'),
path('ejobs/<int:a>/',views.editjobs,name='editjob'),
path('updf/',views.updf,name='update'),
path('pro/',views.profile,name='profile'),
path('ch/',views.cgf,name='cg'),
path('rst/',ad.PasswordResetView.as_view(template_name='html/resetpassword.html'),name='reset_password'),
path('rst_done/',ad.PasswordResetDoneView.as_view(template_name='html/resetpassworddone.html'),name="password_reset_done"),
path('rst_confirm/<uidb64>/<token>/',ad.PasswordResetConfirmView.as_view(template_name='html/resetpasswordconfirm.html'),name='password_reset_confirm'),
path('rst_cmplt/',ad.PasswordResetCompleteView.as_view(template_name='html/reset_password_complete.html'),name="password_reset_complete"),
path('viewjob/',views.viewjob,name='view'),
# path('delt/<int:id>/',views.deledata,name='delete'),
path('jobinfo/',views.jobinfo,name='jinfo'),
path('studinfo/',views.studentinfo,name='stdinfo'),
]

Revised/RevisedApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class User(AbstractUser):
	t=[('CSE','CSE'),('ECE','ECE'),('CIVIL','CIVIL'),('Mechanical','Mechanical'),('EEE','EEE'),('MBA','MBA')]
	y=[('III','III'),('IV','IV')]
	rollno=models.CharField(default='17AK1A000',max_length=10)
	dob=models.DateField(null=True)
	year=models.CharField(choices=y,max_length=5,null=True)
	dept=models.CharField(choices=t,max_length=12,null=True)
	phone_no=models.IntegerField(null=True)
	percentage=models.IntegerField(null=True)
	backlogs=models.IntegerField(null=True)
	pass_year=models.IntegerField(null=True)
	address=models.CharField(max_length=250,null=True)
	r=[(1,'coordinator'),(2,'Student'),(3,'Guest')]
	role=models.IntegerField(choices=r,default=3)



class Coordinator(models.Model):
	t=[('CSE','CSE'),('ECE','ECE'),('CIVIL','CIVIL'),('Mechanical','Mechanical'),('EEE','EEE'),('MBA','MBA')]
	cord_name=models.CharField(max_length=10,null=True)
	dept=models.CharField(choices=t,max_length=12,null=True)
	phone_no=models.IntegerField(null=True)


class Jobinfo(models.Model):
	title=models.CharField(max_length=25)
	location=models.CharField(max_length=20)
	salary=models.IntegerField(null=True)
	skills=models.CharField(max_length=30)
	job_role=models.CharField(max_length=30)
	eligible_percent=models.IntegerField(null=True)
	eligible_dept=models.CharField(max_length=30)
	year_of_pass=models.IntegerField(null=True)
	last_date=models.DateField(null=True)
	descrip=models.CharField(max_length=250)
	com_image=models.ImageField(upload_to='Jobs/',default='123.jpg')

Revised/RevisedApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm
from RevisedApp.models import User,Jobinfo,Coordinator

class UsForm(UserCreationForm):
	password1=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"password"}))
	password2=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"confirm password"}))
	class Meta:
		model=User
		fields=["username"]
		widgets={
		 "username":forms.TextInput(attrs={"class":"form-control","placeholder":"username"}),
		}

class Cordform(forms.ModelForm):
	class Meta:
		model= Coordinator
		fields= ["cord_name","dept","phone_no"]
		widgets={
		 "cord_name":forms.TextInput(attrs={"class":"form-control","placeholder":"Enter your name"}),
		"dept":forms.Select(attrs = {"class": "form-control",}),
		"phone_no":forms.NumberInput(attrs = {"class": "form-control","placeholder":"Enter your Phone number","required":True}),
		}

class Usperm(forms.ModelForm):
	class Meta:
		model = User
		fields=["username","role"]
		widgets={
		 "username":forms.TextInput(attrs={"class":"form-control","readOnly":True,}),
		 "role":forms.Select(attrs={"class":"form-control"}),
		}


class Jobform(forms.ModelForm):
	class Meta:
		model= Jobinfo
		fields = ["title","location","salary","job_role","skills","descrip"]
		widgets={
		"title":forms.TextInput(attrs={"class":"form-control","placeholder":"Enter company name"}),
		"location":forms.TextInput(attrs={"class":"form-control","placeholder":"Job Location"}),
		"salary":forms.NumberInput(attrs={"class":"form-control","placeholder":"Salary"}),
		"job_role":forms.TextInput(attrs={"class":"form-control","placeholder":"Job Role"}),
		"skills":forms.TextInput(attrs={"class":"form-control","placeholder":"Skills requried"}),
		"descrip":forms.TextInput(attrs={"class":"form-control","placeholder":"Description"})
		}

class UpJobform(forms.ModelForm):
	class Meta:
		model= Jobinfo
		fields= ["job_role","eligible_percent","eligible_dept","year_of_pass","last_date","com_image"]
		widgets={
		"job_role":forms.TextInput(attrs={"class":"form-control","placeholder":"Job role"}),
		"eligible_percent":forms.TextInput(attrs={"class":"form-control","placeholder":"eligible percent"}),
		"eligible_dept":forms.TextInput(attrs={"class":"form-control","placeholder":"eligible_dept"}),
		"year_of_pass":forms.NumberInput(attrs={"class":"form-control","placeholder":"year_of_pass"}),
		"last_date":forms.DateInput(attrs = {"class": "form-control","placeholder":"Last date to apply"},),
		}

class UtupForm(forms.ModelForm):
	class Meta:
		model=User
		fields=["username","email","rollno","dob","year","dept","phone_no","percentage","backlogs","pass_year","address"]
		widgets= {
		"username":forms.TextInput(attrs = {"class": "form-control","placeholder":"Enter your name","required":True}),
		"email":forms.EmailInput(attrs = {"class": "form-control","placeholder":"Enter your Email","required":True}),
		"rollno":forms.TextInput(attrs = {"class": "form-control","placeholder":"Enter your Roll no","required":True}),
		"dob":forms.DateInput(attrs = {"class": "form-control",}),
		"year":forms.Select(attrs = {"class": "form-control",}),
		"dept":forms.Select(attrs = {"class": "form-control",}),
		"phone_no":forms.NumberInput(attrs = {"class": "form-control","placeholder":"Enter your Phone number","required":True}),
		"percentage":forms.NumberInput(attrs = {"class": "form-control","placeholder":"Enter your Percentage","required":True}),
		"backlogs":forms.NumberInput(attrs = {"class": "form-control","placeholder":"Enter your Backlogs","required":True}),
		"pass_year":forms.NumberInput(attrs = {"class": "form-control","placeholder":"Enter your year of pass","required":True}),
		"address":forms.TextInput(attrs = {"class": "form-control","placeholder":"Enter your address","required":True}),
		}

class ChpwdForm(PasswordChangeForm):
	old_password=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Enter your old password"}))
	new_password1=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Enter your new password"}))
	new_password2=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Enter your new confirmation password"}))
	class Meta:
		model=User
		fields="__all__"

Revised/RevisedApp/views.py
from django.shortcuts import render,redirect
from RevisedApp.forms import UsForm,Usperm,Jobform,UpJobform,UtupForm,ChpwdForm
from django.core.mail import EmailMessage
from Revised import settings
from RevisedApp.models import User,Jobinfo

# Create your views here.

def homepage(request):
	return render(request,'html/home.html')

def register(request):
	if request.method=="POST":
		t=UsForm(request.POST)
		if t.is_valid():
			t.save()
			return redirect('/lg')
	y=UsForm()
	return render(request,'html/register.html',{'t':y})

def role(request):
	# mnp = Jobinfo.objects.all()
	return render(request,'html/mp.html')

def requestform(request):
	if request.method == "POST":
		u=request.POST.get('username')
		r=request.POST.get('rollno')
		d=request.POST.get('dept')
		e=request.POST.get('email')
		at=request.FILES['fe']
		y="Regarding approve request of "+u
		# t= mail_admins("Usesr Role",y)
		t=EmailMessage("Usesr approval",y,settings.EMAIL_HOST_USER,[settings.ADMINS[0][1],e])
		t.content_subtype= 'html'
		t.attach(at.name,at.read(),at.content_type)
		t.send()
		if t == 1:
			return redirect('/req')
	return render(request,'html/request.html')

def permissions(request):
	ty=User.objects.all()
	return render(request,'html/permissions.html',{'q':ty})

def gvper(request,k):
	r=User.objects.get(id=k)
	if request.method == "POST":
		k=Usperm(request.POST,instance=r)
		if k.is_valid():
			k.save()
			return redirect('/per')
	k2= Usperm(instance=r)
	return render(request,'html/gvp.html',{'y':k2})

def dashboard(request):
	return render(request,'html/dashboard.html')

def jobposts(request):
	w = Jobinfo.objects.all()
	if request.method== "POST":
		e = Jobform(request.POST)
		if e.is_valid():
			e.save()
			return redirect('/jobs')	
	e=Jobform()
	return render(request,'html/jobs.html',{'z':e,'y':w})


def editjobs(request,a):
	t= Jobinfo.objects.get(id=a)
	if request.method== "POST":
		k= UpJobform(request.POST,instance=t)
		if k.is_valid():
			k.save()
			return redirect('/jobs')
	k2 = UpJobform(instance=t)
	return render(request,'html/editjobs.html',{'b':k2})



def profile(req):
	return render(req,'html/profile.html')


def updf(request):
	if request.method == "POST":
		v=UtupForm(request.POST,instance=request.user)
		if v.is_valid():
			v.save()
			return redirect('/pro')
	z=UtupForm(instance=request.user)
	return render(request,'html/updateprofile.html',{'p':z})
	

def cgf(request):
	if request.method == "POST":
		c=ChpwdForm(request.user,data=request.POST)
		if c.is_valid():
			c.save()
			return redirect('/lg')
	c=ChpwdForm(user=request)
	return render(request,'html/changepassword.html',{'p':c})

def viewjob(request):
	return render(request,'html/viewjob.html')

# def deledata(req,id):
# 	data=Jobinfo.objects.get(id=id)
# 	if req.method=="POST":
# 		data.delete()
# 		return redirect('/jobs')
# 	return render(req,'html/deletejob.html',{'sd':data})


def jobinfo(request):
	a = Jobinfo.objects.all()
	return render(request,'html/jobinfo.html',{'t':a})

# def studentinfo(request):
# 	if request.method == "POST":
# 		sid= request.POST['student_id']
# 		c = User(request.POST,instance=request.rollno)
# 		if c.is_valid():
# 			c.save()
# 			return redirect('/studinfo')
# 	b = User.objects.filter(role=2)
# 	return render(request,'html/studentinfo.html',{'u':b})


def studentinfo(request):
	b = User.objects.filter(role=2)
	return render(request,'html/studentinfo.html',{'u':b})

Revised/RevisedApp/templates/html/changepassword.html
{% extends 'html/base.html' %}
{% block title %}Change Password {% endblock %}
{% block content %}
<div class="container">
	<div class="card col-md-6 mx-auto mt-4 p-2 shadow-lg">
		<div class="card-body">
			<h3 class="bg-warning text-center text-light p-2 border rounded"> Change Password</h3>
			<form method="POST">
				{% csrf_token %}
				<table class="table table-borderless">
					{% for i in p %}
					<tr>
						<td>{{i}}</td>
					</tr>
					{% endfor %}
				</table>
				<input type="submit" value="Change" class="form-control btn btn-success btn-block my-2 ">
			</form>
			
		</div>
	</div>
</div>
{% endblock %}

Revised/RevisedApp/templates/html/dashboard.html
{% extends 'html/base.html' %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<div class="container">
	<div class="jumbotron mt-5">
		<h3>
			{% if user.is_superuser %}
			<h3>Admin Dashboard</h3>
			{% elif user.role == 1%}
			<h3>Coordinator Dashboard</h3>
			{% else %}
			<h3>Student Dashboard</h3>
		    {% endif %}
	</div>
</div>

{% endblock %}

Revised/RevisedApp/templates/html/deletejob.html
{% extends 'html/base.html' %}
{% block title %} Delete job{% endblock %}
{% block content %}
<div class="container">
	<div class="card card-md-5 mt-5 mx-auto">
		<div class="card-body mx-3">
			<form method="post">
			{% csrf_token %}
			<h3 class="bg-secondary text-center border rounded text-light">Delete User</h3>
			<p>Are You sure you need to Delete the user {{d.username}}</p>
			<input type="submit" value="Yes Confirm" class="btn btn-success">
			<a href="{% url 'per' %}" class="btn btn-danger">No</a>
		</form>
		</div>
	</div>
</div>
{% endblock %}

Revised/RevisedApp/templates/html/editjobs.html
{% extends 'html/base.html' %}
{% block title %} Job Edit {% endblock %}
{% block content %}


<div class = "container mt-4">
	<div class="card col-md-6 mx-auto">
		<div class="card-body">
		<form method="POST">
			{% csrf_token %}
		<h3>Edit jobs</h3>
		<table class="table table-borderless">
			{% for m in b %}
			<tr>
				<td>{{m}}</td>
			</tr>
			{% endfor %}
		</table>
		<div class="row">
			<div class="col">
				<input type="submit" value="Update Job" class="from-control btn btn-success my-2">
				</div>
			</div>
		</form>
			
	</div>	
	</div>
</div>
<script>
  $( function() {
    $("#id_last_date").datepicker();
  } );
  </script>
{% endblock %}

Revised/RevisedApp/templates/html/home.html
{% extends 'html/base.html' %}
{% block title %} Home {% endblock %}
{% block content %}

<div class="container mt-4">
	<div class="row ">
		<div class="col">
			<h3> CRT</h3>
		
	</div>
</div>
{% endblock %}

Revised/RevisedApp/templates/html/jobs.html
{% extends 'html/base.html' %}
{% block title %}Jobs{% endblock %}
{% block content %}
<div class="container-fluid mt-4">
	<div class="row">
		<div class="col col-md-4 ">
			<div class="card shadow-lg">
				<div class="card-body">
					<h3>Add job</h3>
					<form method="POST">
						{% csrf_token %}
						<table class="table table-borderless">
							<tr>{{z.as_p}}</tr>
						</table>
						<input type="submit" name="Submit" class="btn btn-success col-sm">
                    </form>
                </div>
            </div>
		</div>
		<div class="col col-md ">
			<div class="card shadow-lg">
				<div class="card-body">  
					<h3>Jobs table</h3>
					<table class="table table-borderless">
						<tr class="bg-dark text-light">
							<th>Sno</th>
							<th>Title</th>
							<th>Location</th>
							<th>Salary</th>
							<th>Job Role</th>
							<th>Actions</th>

						</tr>
						{% for t in y %}
						<tr>
							<td>{{forloop.counter}}</td>
							<td>{{t.title}}</td>
							<td>{{t.location}}</td>
							<td>{{t.salary}}</td>
							<td>{{t.job_role}}</td>
							<td colspan="3">
						<a href="{% url 'editjob' t.id %}" class="btn btn-success">Update</a>
						<!-- <a href="#" class="btn btn-info">Update</a> -->
						<a href="#" class="btn btn-danger">Delete</a>
						
					</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			
		</div>
	</div>
</div>
<script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
{% endblock %}

Revised/RevisedApp/templates/html/login.html
{% extends 'html/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<div class = "container">
  <div class = "card col-md-6 mx-auto mt-5 shadow-lg">
    <h3 class="text-center bg-info p-2 my-2 border rounded">Login</h3>
    <div class="card-body">
		<form method="POST">
			{% csrf_token %}
	      <input type="text" name="username" placeholder="Enter your name" class="form-control my-2">
	      <input type="password" name="password" placeholder=" Enter your password" class="form-control my-2">
	</div>
	<div class="row">
        <div class="col">
            <input type="submit" value="Login" class="btn btn-success col-sm">  
        </div>
        <div class="col">
           <a href="{% url 'reges' %}" class="btn btn-secondary col-sm">New User</a>           
        </div>
      </div>

      </form>
      <a href="{% url 'reset_password' %}" class="btn btn-danger btn-block my-2 ">Forgot password ?</a>
  </div>
	</div>
</div>
{% endblock %}

Revised/RevisedApp/templates/html/logout.html
{% extends 'html/base.html' %}
{% block title %} Logout {% endblock %}
{% block content %}

<div class="container">
	<div class="card col-md-6 mx-auto mt-4">
		<h3 class="bg-primary text-white text center">Logout</h3>
		<div class="card-body">
			<h2>Successfully logged out</h2>
			<h3> You need to login again click here<a href="{% url 'log' %}" class="form-control btn btn-warning"> Proceed </a></h3>
			
		</div>
	</div>
</div>
{% endblock %}

Revised/RevisedApp/templates/html/profile.html
{% extends 'html/base.html' %}
{% block title %} Profile {% endblock %}
{% block content %}
<div class="container">
	<div class="row">
	<div class="col-md-4 h-20 mt-4 card shadow-lg">
		<h3 class="p-2 bg-secondary text-center text-light border rounded my-2">Info</h3>
		<img src="{{user.improfile.impf.url}}" height=230px width=100%>
		<div class="card-body">
			<h4>Hi {{user.username}}</h4>
			<div class="row">
				<div class="col">
					<a href="{% url 'dash' %}" class="form-control btn btn-info">Back</a>
				</div>
				<div class="col">
					<a href="{% url 'update' %}" class="form-control btn btn-info">Update</a>
				</div>	
			</div>
		</div>
	</div>
	<div class="col-md-4 mt-4 card shadow-lg">
		<h3 class="p-2 bg-secondary text-center text-light border rounded my-2">User Details</h3>
		<table>
			<tr>
				<th>Username</th>
				<th>{{user.username}}</th>
			</tr>
			<tr>
				<th>Email</th>
				<th>{{user.email}}</th>
			</tr>
		</table>
	</div>
</div>
</div>
{% endblock %}

Revised/RevisedApp/templates/html/register.html
{% extends 'html/base.html' %}
{% block title %}Register{% endblock %}
{% block content %}

<div class="container">
	<div class = "card col-md-6 mx-auto mt-5 shadow-lg">
    <div class="card-body">
		<form method="POST">
	      {% csrf_token %}
	      <h3>Registration</h3>
	      <table class="table table-borderless">
					{% for k in t %}
					<tr>
						<td>
						{{k}}	
						</td>
					</tr>
					{% endfor %}
				</table>
				<div class="row">
					<div class="col">
						<a href="{% url 'log' %}" class="form-control btn btn-info col-sm">Existing user</a>
						</div>
						<div class="col">
							<input type="submit" class="form-control btn btn-success col-sm" name="Subscribe">
						</div>
					</div>
      </form>
     
  </div>
	</div>
	
</div>
{% endblock %}

Revised/RevisedApp/templates/html/request.html
{% extends 'html/base.html' %}
{% block title %}Request{% endblock %}
{% block content %}
<div class="container mt-5">
	<div class="card col-md-6 mx-auto mt-5 shadow-lg">
		<h3>Request Form</h3>
		<div class="card-body">
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
		<input type="text" name="username" class="form-control my-2" placeholder="Enter name">
		<input type="text" name="rollno" class="form-control my-2" placeholder="Enter your Roll number">
		<input type="text" name="dept" class="form-control my-2" placeholder="Enter your department">
		<input type="file" name="fe" class="form-control my-2" placeholder="select your files">
		<input type="email" name="email" class="form-control my-2" placeholder="Enter your mail">
		 <input type="submit" value="Send" class="btn btn-success col-sm">  
		</form>
	</div>
</div>
	
</div>
{% endblock %}

Revised/RevisedApp/templates/html/resetpassword.html
{% extends 'html/base.html' %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div class="container">
	<div class="card col-md-4 mx-auto mt-4 p-2 shadow-lg">
		<div class="card-body">
			<h3 class="text-light text-center bg-dark mt-2 p-2 border rounded">Reset Password Email</h3>
			<form method="POST">
				{% csrf_token %}
				<!-- {{form.as_p}} -->
			<input type="email" name="email" class="form-control my-2" placeholder="Enter your mail Id">
			<input type="submit" value="submit" class="btn btn-success btn-block">
			</form>
		</div>
		
	</div>
	
</div>
{% endblock %}

Revised/RevisedApp/templates/html/updateprofile.html
{% extends 'html/base.html' %}
{% block title %}Update User Details{% endblock %}
{% block content %}
<div class="container mt-4">
	<div class="card col-md-6 mx-auto">
		<div class="card-body">
			<h3>Donor details</h3>
			<form method="POST">
				{% csrf_token %}
				{{p.as_p}}
				<input type="submit" value="Submit" class="btn btn-success">
			</form>
		</div>
	</div>
</div>
 <script>
  $( function() {
    $( "#id_dob" ).datepicker();
  } );
  </script>
{% endblock %}

Revised/RevisedApp/templates/html/viewjob.html
{% extends 'html/base.html' %}
{% block title %}View Job{% endblock %}
{% block content %}

<div class="container">
	<div class="row">
	<div class="col-md-4 h-20 mt-4 card shadow-lg">
		<h3 class="p-2 bg-secondary text-center text-light border rounded my-2">Job info</h3>
		<img src="{{user.improfile.impf.url}}" height=230px width=100%>
		<div class="card-body">
			<h4>Hi {{user.username}}</h4>
			<div class="row">
				<div class="col">
					<a href="{% url 'dash' %}" class="form-control btn btn-info">Back</a>
				</div>
				{% if not user.is_superuser %}
				<div class="col">
					<a href="#" class="form-control btn btn-info">Apply</a>
				</div>	
				{% endif %}
			</div>
		</div>
	</div>
	<div class="col-md-8 mt-4 card shadow-lg">
		<h3 class="p-2 bg-secondary text-center text-light border rounded my-2">Job Details</h3>
		<table>
			<tr>
				<th>Company</th>
				<th>{{user.jobinfo.title}}</th>
			</tr>
			<tr>
				<th>Job Role</th>
				<td>{{user.jobinfo.job_role}}</td>
			</tr>
			<tr>
				<th>Location</th>
				<th>{{user.jobinfo.location}}</th>
			</tr>
			<tr>
				<th>Salary</th>
				<td>{{user.jobinfo.salary}}</td>
			</tr>
			<tr>
				<th>Skills Required</th>
				<td>{{user.jobinfo.skills}}</td>
			</tr>
			<tr>
				<th>Eligible Percentage</th>
				<td>{{user.jobinfo.eligible_percent}}</td>
			</tr>
			<tr>
				<th>Eligible Streams</th>
				<td>{{user.jobinfo.eligible_dept}}</td>
			</tr>
			<tr>
				<th>Year of Pass</th>
				<td>{{user.jobinfo.year_of_pass}}</td>
			</tr>
			<tr>
				<th>Last Date to Apply</th>
			    <td>{{user.jobinfo.last_date}}</td>
		    </tr>
		    <tr>
		    	<th>Description</th>
		    	<td>{{user.jobinfo.descrip}}</td>
		    </tr>
		</table>
	</div>
</div>
</div>
{% endblock %}